### ISSUE TITLE
Rework Ardui html UI with react

### ISSUE THREAD

**Issue by elkasimi** [targist/ardui#19]
Actually the HTML UI is with vanilla JS.

logs are retrieved via a setInterval(func,timeout).
Would be better to rework it with React + TypeScript and retrieve logs with WebSockets instead.

**Comment by yousfiSaad** [comment]
`npm run dev` to run the server in dev mode, you can edit client-side code, the page refreshes automatically
`npm run run` to build the code and serve the UI from dist folder
